pruebas_index:
    path: /pruebas/{lang}/{name}/{page}
    defaults: {_controller: AppBundle:pruebas:index, lang: es, name: Gonzalez, page: 1}
    methods: [GET, POST]
    requirements:
        #accepta caracteres y números
        #name: \w+
        #accepta solo caracteres
        name: "[a-zA-Z]*"
        page: \d+
        lang: es|en|fr
        
pruebas_create:
    path: /pruebas/create
    defaults: {_controller: AppBundle:pruebas:create}
    
pruebas_read:
    path: /pruebas/read
    defaults: {_controller: AppBundle:pruebas:read}
    
pruebas_update:
    path: /pruebas/update/{id}/{titulo}/{descripcion}/{precio}
    defaults: {_controller: AppBundle:pruebas:update}
    
pruebas_delete:
    path: /pruebas/delete/{id}
    defaults: {_controller: AppBundle:pruebas:delete}
    
pruebas_native:
    path: /pruebas/native
    defaults: {_controller: AppBundle:pruebas:nativeSql}
    
pruebas_docquerylang:
    path: /pruebas/docquerylang
    defaults: {_controller: AppBundle:pruebas:docquerylang}
    
pruebas_querybuilder:
    path: /pruebas/querybuilder
    defaults: {_controller: AppBundle:pruebas:createQueryBuilder}
    
pruebas_querybuilder2:
    path: /pruebas/querybuilder2
    defaults: {_controller: AppBundle:pruebas:createQueryBuilder2}
    
pruebas_form:
    path: /pruebas/form
    defaults: {_controller: AppBundle:pruebas:form}
    
pruebas_validar-email:
    path: /pruebas/validar-email/{email}
    defaults: {_controller: AppBundle:pruebas:validarEmail}